server:
  port: 5555
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false
spring:
  application:
    name: zuul
zuul:
  routes:
    organization: /organization/**
    licenses: /licenses/**
    user: /user/**
  ignored-services: '*'
  prefix: /api
  #全部服务服务敏感头(都可传递cookie)
  sensitive-headers:

#nofilter:
#  url: /cloud/conl/test/user/noValidate
